version: '3.3'
services:
  alarcha:
    image: alarcha:latest
    restart: always
    ports:
      - 8080:8080 # <PORT EXPOSED>:<PORT WITHIN CONTAINER>
    expose:
      - '8080'
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'may_prototype'
      MYSQL_ROOT_PASSWORD: '--'
    ports:
      - '6603:6603' # <PORT EXPOSED>:<PORT WITHIN CONTAINER>
    expose:
      - '6603'
    volumes:
      - ./db:/var/lib/mysql
