version: '3.3'
services:
  alarcha:
    image: alarcha:latest
    restart: always
    ports:
      - 8080:8080 # <PORT EXPOSED>:<PORT WITHIN CONTAINER>
    expose:
      - '8080'
    depends_on:
      - db
# you might want to remove the db service since you are using an external database
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '--'
      MYSQL_USER: '--'
      MYSQL_PASSWORD: '--'
    ports:
      - '3306:3306' # <PORT EXPOSED>:<PORT WITHIN CONTAINER>
    expose:
      - '3306'
    command: --init-file /database/create.sql
    volumes:
      - ./create.sql:/database/create.sql
      - ./db:/var/lib/mysql
#----------------------------------------------------------------------------------

